In [1]:
import numpy as np

In [3]:
a= np.random.randint(10,50, size=(5,4), dtype="int16")
np.shape(a)

(5, 4)

In [8]:
arr= np.array([1,2,3,4,5])

In [9]:
print(arr[3])

4


In [11]:
arr[2::1]

array([3, 4, 5])

In [13]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [14]:
a


array([[24, 37, 36, 38],
       [25, 24, 41, 14],
       [25, 31, 30, 46],
       [23, 20, 24, 27],
       [41, 31, 25, 38]], dtype=int16)

In [15]:
a[2,-1]

np.int16(46)

In [17]:
a[-1,-1]

np.int16(38)

In [18]:
a[:-1]

array([[24, 37, 36, 38],
       [25, 24, 41, 14],
       [25, 31, 30, 46],
       [23, 20, 24, 27]], dtype=int16)

SLICING 2D ARRAY
First rows sliced and after columns


In [19]:
a[::]

array([[24, 37, 36, 38],
       [25, 24, 41, 14],
       [25, 31, 30, 46],
       [23, 20, 24, 27],
       [41, 31, 25, 38]], dtype=int16)