In [2]:
import numpy as np

In [3]:
a= np.random.randint(10,30, size= (5,2,3))

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [6]:
a.dtype

dtype('int32')

In [7]:
a.T

array([[[20, 20, 10, 17, 23],
        [10, 21, 15, 15, 21]],

       [[22, 20, 15, 18, 19],
        [27, 18, 19, 11, 19]],

       [[21, 11, 28, 22, 22],
        [17, 28, 20, 16, 10]]], dtype=int32)

In [8]:
a.size

30

In [9]:
a= np.random.randint(10,50, size=(5,4), dtype="int16")
a

array([[11, 22, 16, 27],
       [24, 42, 49, 14],
       [41, 39, 14, 31],
       [23, 34, 15, 47],
       [15, 30, 38, 27]], dtype=int16)

In [ ]:
a.reshape(5,2,2)
a.reshape(5,2,-1) #checks however remaining automatically 

array([[[11, 22],
        [16, 27]],

       [[24, 42],
        [49, 14]],

       [[41, 39],
        [14, 31]],

       [[23, 34],
        [15, 47]],

       [[15, 30],
        [38, 27]]], dtype=int16)

In [17]:
a.flatten() #turns it to linear shape like a list

array([11, 22, 16, 27, 24, 42, 49, 14, 41, 39, 14, 31, 23, 34, 15, 47, 15,
       30, 38, 27], dtype=int16)

In [18]:
a.sum()

np.int64(559)

In [ ]:
a.sum(axis=0) #vertical add

array([114, 167, 132, 146])

In [ ]:
a.sum(axis=1) #horizontal add

array([ 76, 129, 125, 119, 110])

In [21]:
a.trace() #diagonal sum

np.int64(114)

In [22]:
a.cumsum(axis=1)

array([[ 11,  33,  49,  76],
       [ 24,  66, 115, 129],
       [ 41,  80,  94, 125],
       [ 23,  57,  72, 119],
       [ 15,  45,  83, 110]])

In [25]:
a.prod(axis=0)

array([ 3734280, 36756720,  6256320, 14870142])

In [24]:
a.cumprod(axis=1)

array([[    11,    242,   3872, 104544],
       [    24,   1008,  49392, 691488],
       [    41,   1599,  22386, 693966],
       [    23,    782,  11730, 551310],
       [    15,    450,  17100, 461700]])

In [26]:
a

array([[11, 22, 16, 27],
       [24, 42, 49, 14],
       [41, 39, 14, 31],
       [23, 34, 15, 47],
       [15, 30, 38, 27]], dtype=int16)

In [ ]:
a.argmax() #index of max value

np.int64(6)

In [28]:
a.clip(min=20, max=40)

array([[20, 22, 20, 27],
       [24, 40, 40, 20],
       [40, 39, 20, 31],
       [23, 34, 20, 40],
       [20, 30, 38, 27]], dtype=int16)

In [31]:
arr1=np.random.randint(1,100,size=(3,3))
arr2=np.random.randint(1,100,size=(3,3))

In [32]:
arr1,arr2

(array([[50, 96, 88],
        [74, 90, 60],
        [ 9, 24, 33]], dtype=int32),
 array([[16, 23, 78],
        [49, 67, 68],
        [45, 21, 43]], dtype=int32))

In [ ]:
np.concatenate([arr1,arr2])
np.concatenate([arr1,arr2], axis=0) #it's the default so dont have to do this
np.concatenate([arr1,arr2], axis=1)

array([[50, 96, 88, 16, 23, 78],
       [74, 90, 60, 49, 67, 68],
       [ 9, 24, 33, 45, 21, 43]], dtype=int32)

In [39]:
np.vstack([arr1,arr2])
np.hstack([arr1,arr2])

array([[50, 96, 88, 16, 23, 78],
       [74, 90, 60, 49, 67, 68],
       [ 9, 24, 33, 45, 21, 43]], dtype=int32)