In [1]:
import numpy as np

In [9]:
a= np.array([
    [4,5,8],
    [1,2,4]
]
)

b= np.random.randint(1,45, size= (2,3))
c= np.linspace((0,5), (60,100), num=4,dtype=int)

In [10]:
a,b

(array([[4, 5, 8],
        [1, 2, 4]]),
 array([[ 5, 14, 11],
        [26, 39,  4]], dtype=int32))

In [11]:
np.add(a,b)

array([[ 9, 19, 19],
       [27, 41,  8]])

In [12]:
np.pow(a,2)

array([[16, 25, 64],
       [ 1,  4, 16]])

In [13]:
quo,rem= np.divmod(b,a)
rem

array([[1, 4, 3],
       [0, 1, 0]])

TRIGONOMETRIC OPERATIONS

In [14]:
np.sin(a)

array([[-0.7568025 , -0.95892427,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [20]:
cot=np.reciprocal(np.tan(b))
cot

array([[-0.29581292,  0.13803372, -0.00442574],
       [ 0.84835375,  0.27665927,  0.86369115]])

In [21]:
np.positive(cot)
np.negative(cot)

array([[ 0.29581292, -0.13803372,  0.00442574],
       [-0.84835375, -0.27665927, -0.86369115]])

ROUNDING OPERATIONS

In [17]:
np.around(cot,2)

array([[-0.3 ,  0.14, -0.  ],
       [ 0.85,  0.28,  0.86]])

In [18]:
np.floor(cot)

array([[-1.,  0., -1.],
       [ 0.,  0.,  0.]])

In [19]:
np.ceil(cot)

array([[-0.,  1., -0.],
       [ 1.,  1.,  1.]])

Matrix Operation

In [34]:
bT=np.transpose(b)

In [39]:
# All possible matrix multi methods
a @ bT #discouraged method
np.dot(a,bT)
res=a.dot(bT) 

In [40]:
#Trace
d_sum= np.trace(res)
print(d_sum)

298


In [41]:
#Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [45]:
#determinant
d= np.random.randint(1,45, size= (3,3))
det_d=np.linalg.det(d) #only square matrix can have determinants

In [48]:
#inverse
inv_d= np.linalg.inv(d)
inv_d

array([[-0.00453139,  0.04630858, -0.02077807],
       [-0.07847038,  0.0214412 ,  0.05481874],
       [ 0.06498674, -0.05437666,  0.00530504]])

In [73]:
matX= np.array([
            [4,2],
            [5,3]
        ])
matY= np.array([8,9])
matY

array([8, 9])

In [70]:
inv_matX= np.linalg.inv(matX)

In [74]:
res= np.dot(inv_matX, matY)
res

array([ 3., -2.])

In [ ]:
#array broadcasting